### ISSUE TITLE
Ascii-Table will not work if Rows only contains one element

### ISSUE THREAD

**Issue by azngeek** [flow-php/etl#259]
I was able to reproduce this error: If the rows-entries only contain one single element, then an exception will be thrown. 

```
yield new Rows(
                Row::create(Entry::integer('id', 1), Entry::string('name', 'EN'))
            );
```

Exception

```
Throwmax(): Argument #1 ($value) must be of type array, int given

In AbstractErrorHandler.php line 38:

  [Exception]
  TypeError: max(): Argument #1 ($value) must be of type array, int given in /var/www/share/dev/htdocs/vendor/flow-php/etl/src/Flow/ETL/Formatter/ASCII/ASCIITable.php:176
  Stack trace:
  #0 /var/www/share/dev/htdocs/vendor/flow-php/etl/src/Flow/ETL/Formatter/ASCII/ASCIITable.php(176): max(1)
  #1 /var/www/share/dev/htdocs/vendor/flow-php/etl/src/Flow/ETL/Formatter/ASCII/ASCIITable.php(89): Flow\ETL\Formatter\ASCII\ASCIITable->getColWidths(Array, 20)
  #2 /var/www/share/dev/htdocs/vendor/flow-php/etl/src/Flow/ETL/Formatter/AsciiTableFormatter.php(31): Flow\ETL\Formatter\ASCII\ASCIITable->makeTable(Array, 20)
  #3 /var/www/share/dev/htdocs/vendor/flow-php/etl/src/Flow/ETL/Loader/StreamLoader.php(89): Flow\ETL\Formatter\AsciiTableFormatter->format(Object(Flow\ETL\Rows), 20)
  #4 /var/www/share/dev/htdocs/vendor/flow-php/etl/src/Flow/ETL/Pipeline/SynchronousPipeline.php(66): Flow\ETL\Loader\StreamLoader->load(Object(Flow\ETL\Rows))
  #5 /var/www/share/dev/htdocs/vendor/flow-php/etl/src/Flow/ETL/DataFrame.php(260): Flow\ETL\Pipeline\SynchronousPipeline->process(Object(Flow\ETL\Config))
  #6 /var/www/share/dev/htdocs/bundle/Mothership/YadiBundle/src/Command/AbstractFlowCommand.php(138): Flow\ETL\DataFrame->run()
```

Complete example:

```
        $flow  = new Flow();
        $countries = new Rows(
            Row::create(Entry::integer('id', 1), Entry::string('country', 'EN')),
        );

        $flow->read(From::rows($countries))
            ->write(To::stdout())
            ->run();
```

**Comment by norberttech** [comment]
Thanks for reporting! https://github.com/flow-php/etl/pull/260 should solve the problem!
